# zsh autogenerated config 
HISTFILE=~/.histfile
HISTSIZE=1000
SAVEHIST=1000
bindkey -v

zstyle :compinstall filename '/home/kareem/.zshrc'

autoload -Uz compinit
compinit

# set up colors
autoload -U colors && colors

# environment variables
export CC=clang
export CXX=clang++
export TERMINAL=kitty
export WALLPAPER=~/Pictures/Wallpapers/wave-ctppccn-mocha-mauve.png 
export EDITOR=nvim

# prompt customization
function set_prompt() {
  if [[ $? -ne 0 ]]; then
    STATUS_INDICATOR="%F{red}%f"
  else
    STATUS_INDICATOR="%F{green}%f"
  fi

  PROMPT=" %n@%m 󰉋 %~ 
 $STATUS_INDICATOR "
}

autoload -U add-zsh-hook
add-zsh-hook precmd set_prompt

 # fzf setup
 export FZF_DEFAULT_COMMAND='fd --type f'

fzf_open_nvim() {
  local file
  file=$(fd --type f | fzf --exact) && nvim "$file"
}

open_nvim_widget() {
  zle -I
  fzf_open_nvim
  zle reset-prompt
}

zle -N open_nvim_widget

# nvim setup
launch_nvim() {
  ${EDITOR:-nano}
}

zle -N launch_nvim

# tmux setup
launch_tmux() {
  # Get list of sessions and remove 'dropdown' if present
  sessions=$(tmux list-sessions -F '#S' 2>/dev/null | grep -v '^dropdown$')

  if [ -z "$sessions" ]; then
    read "response?Enter session name: "
    tmux new-session -s "$response"
    return
  fi

  count=$(echo "$sessions" | wc -l | tr -d ' ')  # Strip whitespace

  if [ "$count" -eq 1 ]; then
    only_session="$sessions"

    read "response?Would you like to (a)ttach to '$only_session' or (c)reate a new session? "

    if [ "$response" = "c" ]; then
      read "newname?Enter new session name: "
      tmux new-session -s "$newname"
      return
    elif [ "$response" = "a" ]; then
      tmux attach-session -t "$only_session"
      return
    else
      echo "Invalid response"
      return
    fi
  fi

  # More than one session
  selecter=$(echo "$sessions" | fzf --prompt="Select tmux session: " --height=50% --border=sharp --layout=reverse)
  if [ -n "$selecter" ]; then
    tmux attach-session -t "$selecter"
  fi
}

# aliases
alias cd='z'
alias ls='eza --icons=always'
alias vi='nvim'
alias vim='nvim'
alias grep='rg'
alias find='fd'
alias cat='bat'
alias tm='launch_tmux'

# zoxide init
eval "$(zoxide init zsh)"

# zsh plugins
source ~/.zsh/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh
source ~/.zsh/zsh-autosuggestions/zsh-autosuggestions.zsh

# keybinds
bindkey '^E' launch_nvim
bindkey '^F' open_nvim_widget
